import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTypeScript from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTypeScript,
  // next-env.d.ts is generated by Next and always trips the triple-slash rule.
  globalIgnores([".next/**", ".next-dev/**", "node_modules/**", "out/**", "next-env.d.ts"]),
]);

export default eslintConfig;
